name: thai
channels:
- conda-forge
dependencies:
- aeolus>=0.4.11
- black
- cartopy>=0.18
- dask
- fastprogress
- flake8
- h5netcdf
- ipykernel
- ipywidgets
- iris>=3.0
- latlon23
- loguru
- matplotlib>=3.4
- metpy
- nc-time-axis>=1.2
- netCDF4
- numpy
- pandas
- pip
- pre-commit
- python>=3.9
- pytest
- python-stratify
- scipy
- tqdm
- xarray>=0.17
- windspharm
