name: thai
channels:
- conda-forge
dependencies:
- aeolus>=0.4.8
- black
- cartopy>=0.18
- dask
- fastprogress
- flake8
- h5netcdf
- h5py
- ipykernel
- ipywidgets
- iris>=3.0
- latlon23
- loguru
- matplotlib>=3.0
- metpy
- mo_pack
- netCDF4
- numpy
- pandas
- python>=3.9
- pip
- pytest
- python-stratify
- scipy
- tqdm
- xarray>=0.17
- pip:
  - imageio_ffmpeg
